### ISSUE TITLE
Close button for the modal

### ISSUE THREAD

**Issue by turculaurentiu91** [apideck-libraries/vault-js#12]
Hi, it would be nice to have a close or a cross "X" button for the users to close the modal after they finish their setup. Right now, looks like the only way to close it is to click away on the background.

**Comment by jakeprins** [comment]
Added a close icon on the background to indicate better that it is clickable to close it (the full backdrop is still clickable, not just the icon). In addition you could close the modal from the options dropdown.

![CleanShot 2023-05-15 at 13 58 46](https://github.com/apideck-libraries/vault-js/assets/17762366/836e81d4-cdf5-4bae-8a05-7f851cd2527d)
