### ISSUE TITLE
Vault: Add bottom padding to manage integrations title

### ISSUE THREAD

**Issue by Gdewilde** [apideck-libraries/vault-js#4]
<img width="1728" alt="Screenshot 2023-01-23 at 09 57 52" src="https://user-images.githubusercontent.com/1112129/214000598-390a33c0-c612-4cb1-9bf6-35cd029e8887.png">

**Comment by jakeprins** [comment]
Fixed in version `0.2.31`

**Comment by jakeprins** [comment]
The automation process seems to work well. It's directly fixed in all places VaultJS is being used:

![CleanShot 2023-01-26 at 08.56.01.png](https://images.zenhubusercontent.com/6017aa3c7206f157f396a24f/9dbbc633-7d04-4e51-ad4b-f25f0bf8ddd1)

**Comment by Gdewilde** [comment]
👌🏻  





On Thu, Jan 26, 2023 at 8:59 AM Jake Prins ***@***.***>  wrote:


The automation process seems to work well. It's directly fixed in all places
VaultJS is being used:



—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>



Gertjan De WildeCEO & co-founderApideck
